name: README Update Automation

on:
  pull_request:
    types: [closed]

jobs:
  update-readme:
    name: Update README after PR merge
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      # Check out the repo to access its content
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up Python using the latest stable version
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      # Install Python dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Extract PR Number and Commit SHA from the GitHub event context
      - name: Extract PR Number and Commit SHA
        id: pr_info
        run: |
          echo "PR_NUMBER=$(jq -r '.pull_request.number' $GITHUB_EVENT_PATH)" >> $GITHUB_ENV
          echo "COMMIT_SHA=$(jq -r '.pull_request.merge_commit_sha' $GITHUB_EVENT_PATH)" >> $GITHUB_ENV
      # Run the Python script
      - name: Generate Updated README
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          REPO_PATH: ${{ github.repository }}
          PR_NUMBER: ${{ env.PR_NUMBER }}
          COMMIT_SHA: ${{ env.COMMIT_SHA }}
        run: python main.py

      # Additional step to enable debugging, helps in troublshooting
      - name: Enable Debug Logging
        run: |
          echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV
